function [] = mk_int_msks(PLACE, info, masks)
%% written by K.Garner, 2020
% make masks that are the intersection of the anatomical and the
% distribution of the mean peak info

% idea of this function is to take the mean peak image, and iterate through
% masks (anatomical), for each brain region the distribution of mean peak
% values is selected, and is then segmented according to x criteria. These
% criteria are then used to make n new mask files.

% inputs
% PLACE = where is your data? give the name of your data storage system to
% load the correct template file paths and to load library functions
% info = the information structure generated by mu_images.m (see in this
% folder) 
% masks = array of mask file names