function [] = mu_images(PLACE, info, op)
%% written by K.Garner, 2020
% idea of this function is to average across the images, the criteria of
% which is set by 'op' (see below), using SPM_imcalc, and to save the resulting images
% with a meaningful filename

% inputs
% PLACE = where is your data? give the name of your data storage system to
% load the correct template file paths and to load library functions
% info = the information structure generated by def_pars.m (see in this
% folder)
% op = operation. 'i' = intersection of parameters across sessions - 
%                       i.e. session 1 & 2, mu image 1 & 2 for parameter 1.

% test 1: manual testing of mean operation vs spm imcalc





end